### ISSUE TITLE
Bot left discord server when he start

### ISSUE THREAD

**Issue by Scaff31** [dkoz/ascension-bot#2]
Hello,

I wanted to try your bot, but it turns out that after following the information provided on the wiki. As soon as I launch the bot, either via python main.py or systemctl start ascension.service, the bot immediately quits the discord server. I get the join notifications but at startup it quits the server. Any idea why?

**Comment by dkoz** [comment]
Bot has a whitelist function in the environment file. You will set the `WHITELIST_GUILDS` to your guild id like below.
```
WHITELIST_GUILDS=12345678
```

**Comment by Scaff31** [comment]
Yep i see that just now :) Thx for help 👍

**Comment by Scaff31** [comment]
@dkoz another question for the webhook url you use " or ' for escape ?

**Comment by Scaff31** [comment]
dkoz great work =)

**Comment by dkoz** [comment]
> @dkoz another question for the webhook url you use " or ' for escape ?

Does not matter.
