### ISSUE TITLE
SSL Error when i run Bot on Server

### ISSUE THREAD

**Issue by dtmaster79** [dkoz/ascension-bot#3]
python main.py
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\aiohttp\connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 1148, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 1181, in _create_connection_transport
    await waiter
  File "C:\Python312\Lib\asyncio\sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
  File "C:\Python312\Lib\asyncio\sslproto.py", line 560, in _do_handshake
    self._sslobj.do_handshake()
  File "C:\Python312\Lib\ssl.py", line 916, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Verwaltung\ascension-bot-2.0\main.py", line 61, in <module>
    bot.run(settings.BOT_TOKEN)
  File "C:\Python312\Lib\site-packages\nextcord\client.py", line 878, in run
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\nextcord\client.py", line 857, in runner
    await self.start(*args, **kwargs)
  File "C:\Python312\Lib\site-packages\nextcord\client.py", line 820, in start
    await self.login(token)
  File "C:\Python312\Lib\site-packages\nextcord\client.py", line 657, in login
    data = await self.http.static_login(token.strip())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\nextcord\http.py", line 446, in static_login
    data = await self.request(Route("GET", "/users/@me"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\nextcord\http.py", line 299, in request
    async with self.__session.request(method, url, **kwargs) as response:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\aiohttp\client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\aiohttp\connector.py", line 1257, in _create_direct_connection
    raise last_exc
  File "C:\Python312\Lib\site-packages\aiohttp\connector.py", line 1226, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\aiohttp\connector.py", line 1027, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]

**Comment by dkoz** [comment]
> python main.py Traceback (most recent call last): File "C:\Python312\Lib\site-packages\aiohttp\connector.py", line 1025, in _wrap_create_connection return await self._loop.create_connection(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Python312\Lib\asyncio\base_events.py", line 1148, in create_connection transport, protocol = await self._create_connection_transport( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Python312\Lib\asyncio\base_events.py", line 1181, in _create_connection_transport await waiter File "C:\Python312\Lib\asyncio\sslproto.py", line 578, in _on_handshake_complete raise handshake_exc File "C:\Python312\Lib\asyncio\sslproto.py", line 560, in _do_handshake self._sslobj.do_handshake() File "C:\Python312\Lib\ssl.py", line 916, in do_handshake self._sslobj.do_handshake() ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "E:\Verwaltung\ascension-bot-2.0\main.py", line 61, in bot.run(settings.BOT_TOKEN) File "C:\Python312\Lib\site-packages\nextcord\client.py", line 878, in run return future.result() ^^^^^^^^^^^^^^^ File "C:\Python312\Lib\site-packages\nextcord\client.py", line 857, in runner await self.start(*args, **kwargs) File "C:\Python312\Lib\site-packages\nextcord\client.py", line 820, in start await self.login(token) File "C:\Python312\Lib\site-packages\nextcord\client.py", line 657, in login data = await self.http.static_login(token.strip()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Python312\Lib\site-packages\nextcord\http.py", line 446, in static_login data = await self.request(Route("GET", "/users/@me")) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Python312\Lib\site-packages\nextcord\http.py", line 299, in request async with self.__session.request(method, url, **kwargs) as response: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Python312\Lib\site-packages\aiohttp\client.py", line 1197, in **aenter** self._resp = await self._coro ^^^^^^^^^^^^^^^^ File "C:\Python312\Lib\site-packages\aiohttp\client.py", line 581, in _request conn = await self._connector.connect( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Python312\Lib\site-packages\aiohttp\connector.py", line 544, in connect proto = await self._create_connection(req, traces, timeout) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Python312\Lib\site-packages\aiohttp\connector.py", line 944, in _create_connection _, proto = await self._create_direct_connection(req, traces, timeout) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Python312\Lib\site-packages\aiohttp\connector.py", line 1257, in _create_direct_connection raise last_exc File "C:\Python312\Lib\site-packages\aiohttp\connector.py", line 1226, in _create_direct_connection transp, proto = await self._wrap_create_connection( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Python312\Lib\site-packages\aiohttp\connector.py", line 1027, in _wrap_create_connection raise ClientConnectorCertificateError(req.connection_key, exc) from exc aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]

This is not an issue with the bot, it's an issue with your connection to discord. You can try following this guide here: https://github.com/dkoz/palworld-palbot/wiki/Troubleshooting#unable-to-get-local-issuer-certificate

I cannot guarantee this will solve you issue.

**Comment by dtmaster79** [comment]
yes it solves the problem. I already looked it up in your discord yesterday and fixed it. thanks.

**Comment by dkoz** [comment]
Glad you fixed it!
